### ISSUE TITLE
Status of the Project?

### ISSUE THREAD

**Issue by muhlba91** [jenkinsci/seed-plugin#38]
Hi,

I have seen this project doesn‘t have a lot going on anymore and it seems to be unmaintained. Hence my question what the plan for this plugin is?

Personally, I like this plugin and use it for seeding most of our jobs. However, due to changes in BitBucket and their WebHooks as well as old Gradle and Jenkins version, I am currently putting effort into trying to get those things up to date.

Due to this, the question is as well to whether, once updates are made and working properly, I should create a PR or there‘s the need for either a transition of the project to other people (and group or/and plugin identifier) or to publish it as an entirely „new“ plugin?

Thanks, Daniel :)

**Comment by dcoraboeuf** [comment]
Hi Daniel,

Indeed, not using this plugin any longer in production, I don't maintain it any longer very seriously.

However, feel free to contribute by creating any PR. If you want to go on further, we can always transfer the ownership.

I know that @DavidCADanneels is working with this plugin and could be interested too.

Let me know,
thanks,
Damien

**Comment by muhlba91** [comment]
Hi,

thank you for this information. :)

If you do not maintain the plugin anymore, I'd favor a transfer as it's a core part of our pipelines and will be kept maintained for the time being at least from my side (once tests pass again), if that's alright with you?

Anyhow, I have forked the plugin (https://github.com/muhlba91/seed-plugin) and Travis (https://travis-ci.org/muhlba91/seed-plugin) fails at the moment. I still try to figure out what change causes the failure, especially the integration tests.
I also dropped SVN support as I believe most people/organizations are working with Git nowadays.

**Comment by dcoraboeuf** [comment]
Hi Daniel,

It's really not a problem for me to transfer the ownership of this plugin to you, as I don't foresee a moment when I could go back to it in the next future. We can follow the guidelines at https://wiki.jenkins.io/display/JENKINS/Adopt+a+Plugin

If you're OK, you can post a message on the [developer mailing list](http://jenkins-ci.org/content/mailing-lists). Since the previous committer is still reachable :) this should be approved quite fast for you to have commit rights on this repository.

 @DavidCADanneels , do you want also some commit rights since I know that you're still using this plugin in production?

Best regards,
Damien

PS: about the Git-only support, I understand 100% however this plugin has been born in an organization where SVN was still very active, so many a major version change might be required.

**Comment by DavidCADanneels** [comment]
Hi Damien,

I’m still interested in taking over ownership of the seed-plugin as I mentioned before.
Going for lunch was a good idea, but I prefer to do this handover profoundly,
especially regarding customers: who are the main customers /contributers,
which features are still used, which ones can be deprecated, …

Regarding the support for SVN: indeed, we still use SVN as main SCM source,
although a slow … slow … transition towards Git might … maybe … be planned in the near future.
(Sorry for my cynism)

On the otherhand, I no longer need the BRANCH_SCM parameter for SVN,
by enforcing a strict versioning scheme: branches/<version>
(with branches/ as ignored prefix and no more trunk development)

I also have a open PR to stop injecting Global Passwords in the Generator jobs,
since I found a workaround via the config … inject Credential Bindings closure

Before this handover, it might be better that I check the sources first, to understand the logic …
But I need to find time, and time is very precious …

Feel free to contact me on my mobile number to set an appointment or to discuss.
I’m in Brussels (at least) every Monday and Thursday.

Hear you soon,
David.

________________________________

**Comment by dcoraboeuf** [comment]
Hi David,

As mentioned before, I really don't use this plugin any longer, having switched to other solutions, and I think that both you and @muhlba91 will be able to sort the issues out.

I cannot grant commit rights on this project (I don't own it) hence the need for you both to follow the process indicated at https://wiki.jenkins.io/display/JENKINS/Adopt+a+Plugin 

In short, you need to request some ownership on the dev mailing list and I need to approve. The process can take up to two weeks. So the better the sooner.
